profile:
  value: '현재 프로필은 prod 입니다.😛'


logging:
  level:
    root: info
    '[com.sh.app]': info

spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  sql:
    init:
      mode: never
      data-locations: classpath:sql/data.sql
      schema-locations: classpath:sql/schema.sql
  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}
      password: ${PROD_REDIS_PASSWORD}
